"""empty message

Revision ID: ec143710bb7f
Revises: 
Create Date: 2018-04-23 23:03:04.211521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec143710bb7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.CHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('age', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.CHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'uuid', name='employer_pkey')
    )
    op.drop_table('stations')
    # ### end Alembic commands ###
